#!/usr/bin/env bash
# Deploys the dotfiles in this directory using GNU stow
set -euo pipefail

cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"

for dir in */; do
  echo "Stowing $dir"
  stow -t "$HOME" "$dir" || echo "Error stowing $dir"
done
